baseURL = "https://ilosaurus.github.io/"
languageCode = "id-id"
title = "ilosaurus's"
theme = "PaperMod"

[params]
  mainSections = ["posts"]
  defaultTheme = "light" # auto, dark, light
  ShowShareButtons = true
  ShowReadingTime = true
  ShowCodeCopyButtons = true