# Backend untuk testing lokal, tidak memerlukan otentikasi
local_backend: true

# Backend untuk deployment, akan digunakan saat di-deploy
backend:
  name: github
  repo: ilosaurus/ilosaurus.github.io # Ganti dengan username/repo Anda
  branch: main # Atau master, sesuaikan dengan branch utama Anda

# Lokasi penyimpanan file media (gambar, dll)
media_folder: "static/uploads"
public_folder: "/uploads"

# Mendefinisikan koleksi konten (misal: postingan blog)
collections:
  - name: "blog" # Nama koleksi
    label: "Blog Post" # Label yang muncul di UI Decap
    folder: "content/posts" # Folder tempat menyimpan file .md
    create: true # Izinkan membuat file baru
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Format nama file
    fields: # Daftar field untuk setiap postingan
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }